name: recipestash
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.13.0
  firebase_core: ^2.21.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.6
  path: ^1.8.3
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
