name: recipestash
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.13.0
  firebase_core: ^2.21.0
  firebase_storage: ^11.5.3
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_local_notifications: ^16.1.0
  flutter_share: ^2.0.0
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.1.6
  http: ^1.1.0
  image_picker: ^1.0.4
  path: ^1.8.3
  permission_handler: ^11.0.1
  printing: ^5.11.1
  sqflite: ^2.3.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/Icon.png
    - assets/images/SignInWithGoogle.png
